### ISSUE TITLE
Dynamically linked binary does not distribute

### ISSUE THREAD

**Issue by nedrocks** [wulkano/aperture-node#15]
When compiling the swift code on Big Sur, I am presented with a warning:

```
warning: Swift compiler no longer supports statically linking the Swift libraries. They're included in the OS by default starting with macOS Mojave 10.14.4 beta 3. For macOS Mojave 10.14.3 and earlier, there's an optional Swift library package that can be downloaded from "More Downloads" for Apple Developers at https://developer.apple.com/download/more/
```

The outcome is the binary is dynamically linked to AVFoundation and other packages. This works very well locally but when I go to distribute my app (after signing and notarizing) I get an error from `com.apple.xprotect:xprotect`:

```
File /Applications/Debrief.app/Contents/Resources/app.asar.unpacked/node_modules/@XXXX/aperture/aperture failed on rPathCmd /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftAVFoundation.dylib (rpath resolved to: (path not found), bundleURL: /Applications/XXXX.app)
```

I have attempted to solve this by downgrading the swift compiler and different compiler flags to try and force static linking but to no success. 

Is this a known issue on later versions of Mac OS? Or could this be a user error on my part?

**Comment by sindresorhus** [comment]
I have not seen this issue, but it seems like you managed to solve it: https://forums.swift.org/t/bundle-stdlib-with-swift-binary/43653/5

**Comment by nedrocks** [comment]
Yes I did! Sorry I hadn't yet updated this ticket.

The issue is on newer versions of MacOS you can no longer statically link swift binaries... I also learned from someone at Apple that statically linked binaries may not run in the future so something to keep an eye on!
