### ISSUE TITLE
Can I use it with WebRTC to share my screen?

### ISSUE THREAD

**Issue by LucasBoberg** [wulkano/aperture-node#4]
I plan on building a webRTC app which I can screen share with and I was wondering if this would work for that.

**Comment by sindresorhus** [comment]
This package gives you a file path to a video file. Whether you can use this for WebRTC is not really something I can answer, as I don't have any experience with WebRTC.

**Comment by skllcrn** [comment]
You might want to look into [`getUserMedia`](https://w3c.github.io/mediacapture-screen-share/) 
 @LucasBoberg, additionally @contra has done some excellent [WebRTC work you might want to look into](https://github.com/contra/rtc-everywhere).
